name: cd
permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  workflow_run:
    workflows: ['ci']
    types: [completed]
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-packages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          title: 'ops: version packages'
          commit: 'ops: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
